package tracelens

import (
	"strings"
	"testing"
)

func TestRenderMarkdownReport_IncludesEvidenceAndUnavailableTelemetry(t *testing.T) {
	tr := traj(
		okStep("read", map[string]any{"path": "a"}, "same | value", 0),
		okStep("read", map[string]any{"path": "a"}, "same | value", 0),
		okStep("read", map[string]any{"path": "a"}, "same | value", 0),
	)
	report := Analyze(tr, DefaultConfig())
	got := RenderMarkdownReport(DecodedTrace{Trajectory: tr, Dialect: DialectNeutral}, report, MarkdownReportOptions{Source: "fixture", GeneratedBy: "tracelens report fixture"})
	for _, want := range []string{"# Tracelens diagnostic report", "**Dialect:** `neutral-jsonl`", "| 0 | read | same \\| value |", "Tokens in / out | unavailable", "Generated by"} {
		if !strings.Contains(got, want) {
			t.Fatalf("report missing %q:\n%s", want, got)
		}
	}
}

func TestRenderMarkdownReport_CleanRunIsDeterministic(t *testing.T) {
	tr := traj(okStep("read", nil, "ok", 0))
	report := Analyze(tr, DefaultConfig())
	opts := MarkdownReportOptions{Source: "x", GeneratedBy: "cmd"}
	a := RenderMarkdownReport(DecodedTrace{Trajectory: tr, Dialect: DialectNeutral}, report, opts)
	b := RenderMarkdownReport(DecodedTrace{Trajectory: tr, Dialect: DialectNeutral}, report, opts)
	if a != b || !strings.Contains(a, "No pathologies detected.") {
		t.Fatalf("report is not deterministic or clean: %q", a)
	}
}
