package tracelens

import (
	"fmt"
	"strings"
)

// MarkdownReportOptions supplies deterministic provenance for a portable
// report. GeneratedBy should be the reproducible command, not a timestamp.
type MarkdownReportOptions struct {
	Source      string
	GeneratedBy string
}

// RenderMarkdownReport builds a self-contained, deterministic diagnostic
// artifact. It never re-runs analysis or mutates the supplied trace/report.
func RenderMarkdownReport(decoded DecodedTrace, report Report, opts MarkdownReportOptions) string {
	var b strings.Builder
	b.WriteString("# Tracelens diagnostic report\n\n")
	fmt.Fprintf(&b, "- **Source:** `%s`\n", markdownCode(opts.Source))
	fmt.Fprintf(&b, "- **Dialect:** `%s`\n", decoded.Dialect)
	fmt.Fprintf(&b, "- **Verdict:** `%s` / `%s`\n", report.Decision, report.Tier)
	fmt.Fprintf(&b, "- **Headline:** %s\n", report.Headline)
	fmt.Fprintf(&b, "- **Generated by:** `%s`\n\n", markdownCode(opts.GeneratedBy))

	b.WriteString("## Telemetry\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|---|---:|\n| Steps | %d |\n", report.Steps)
	writeTelemetry(&b, decoded.Trajectory, report)

	b.WriteString("\n## Findings\n\n")
	if len(report.Findings) == 0 {
		b.WriteString("No pathologies detected.\n")
		return b.String()
	}
	byIndex := map[int]Step{}
	for _, step := range decoded.Trajectory.Steps {
		byIndex[step.Index] = step
	}
	for i, finding := range report.Findings {
		fmt.Fprintf(&b, "### %d. %s — %s\n\n", i+1, finding.Severity.String(), finding.Kind)
		fmt.Fprintf(&b, "%s\n\n", finding.Summary)
		fmt.Fprintf(&b, "- **Evidence:** %s\n", locus(finding.Steps))
		fmt.Fprintf(&b, "- **Measured waste:** $%.4f\n", finding.WastedUSD)
		fmt.Fprintf(&b, "- **Repair:** %s\n\n", finding.Repair)
		b.WriteString("| Step | Tool / state | Outcome excerpt |\n|---:|---|---|\n")
		for _, idx := range finding.Steps {
			step, ok := byIndex[idx]
			if !ok {
				fmt.Fprintf(&b, "| %d | _missing normalized step_ | _unavailable_ |\n", idx)
				continue
			}
			fmt.Fprintf(&b, "| %d | %s | %s |\n", idx, markdownCell(stepLabel(step)), markdownCell(stepOutcome(step)))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func writeTelemetry(b *strings.Builder, tr Trajectory, report Report) {
	tokensIn, tokensOut, latency := 0, 0, 0
	hasTokens, hasLatency, hasCost := false, false, false
	for _, step := range tr.Steps {
		tokensIn += step.TokensIn
		tokensOut += step.TokensOut
		latency += step.LatencyMS
		hasTokens = hasTokens || step.TokensIn != 0 || step.TokensOut != 0
		hasLatency = hasLatency || step.LatencyMS != 0
		hasCost = hasCost || step.CostUSD != 0
	}
	if hasTokens {
		fmt.Fprintf(b, "| Tokens in / out | %d / %d |\n", tokensIn, tokensOut)
	} else {
		b.WriteString("| Tokens in / out | unavailable |\n")
	}
	if hasCost {
		fmt.Fprintf(b, "| Total / wasted cost | $%.4f / $%.4f |\n", report.TotalUSD, report.WastedUSD)
	} else {
		b.WriteString("| Total / wasted cost | unavailable |\n")
	}
	if hasLatency {
		fmt.Fprintf(b, "| Recorded latency | %d ms |\n", latency)
	} else {
		b.WriteString("| Recorded latency | unavailable |\n")
	}
}

func stepLabel(step Step) string {
	if step.Tool != "" {
		return step.Tool
	}
	if step.Thought != "" {
		return "assistant thought"
	}
	return step.Role
}

func stepOutcome(step Step) string {
	body := step.Observation
	if step.Error != "" {
		body = "error: " + step.Error
	}
	if body == "" {
		body = step.Thought
	}
	if body == "" && step.IsTool() && step.OK == nil {
		body = "outcome unavailable (call incomplete)"
	}
	return short(body, 160)
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}

func markdownCode(value string) string {
	return strings.ReplaceAll(value, "`", "'")
}
